name: GitHub Actions Demo
run-name: Boilerplate
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Lint
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Test
        run: npm run lint
      - name: WDIO Test
        run: npm run wdio